export default {
  edges: [
    {
      id: "d02f039d-2b2d-46d4-a663-8f3c909efc72",
      text: {
        x: 444.5,
        y: 45,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 509,
        y: 45,
        id: "8_3",
      },
      pointsList: [
        {
          x: 380,
          y: 45,
        },
        {
          x: 509,
          y: 45,
        },
      ],
      properties: {},
      startPoint: {
        x: 380,
        y: 45,
        id: "3_1",
      },
      sourceNodeId: 3,
      targetNodeId: 8,
    },
    {
      id: "280e5854-eba0-4d0f-81ec-e95029e52b5c",
      text: {
        x: 569,
        y: 90,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 568,
        y: 113,
        id: "9_0",
      },
      pointsList: [
        {
          x: 569,
          y: 60,
        },
        {
          x: 569,
          y: 90,
        },
        {
          x: 568.5,
          y: 90,
        },
        {
          x: 568.5,
          y: 83,
        },
        {
          x: 568,
          y: 83,
        },
        {
          x: 568,
          y: 113,
        },
      ],
      properties: {},
      startPoint: {
        x: 569,
        y: 60,
        id: "8_2",
      },
      sourceNodeId: 8,
      targetNodeId: 9,
    },
    {
      id: "4db92089-9d97-48c4-bd47-98a129654a1b",
      text: {
        x: 568,
        y: 272.5,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 569,
        y: 310,
        id: "14_0",
      },
      pointsList: [
        {
          x: 568,
          y: 235,
        },
        {
          x: 568,
          y: 272.5,
        },
        {
          x: 569,
          y: 272.5,
        },
        {
          x: 569,
          y: 310,
        },
      ],
      properties: {},
      startPoint: {
        x: 568,
        y: 235,
        id: "13_2",
      },
      sourceNodeId: 13,
      targetNodeId: 14,
    },
    {
      id: "03be92b9-37bd-4ba3-a8c9-0131d544b11b",
      text: {
        x: 444,
        y: 325,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 379,
        y: 325,
        id: "15_1",
      },
      pointsList: [
        {
          x: 509,
          y: 325,
        },
        {
          x: 379,
          y: 325,
        },
      ],
      properties: {},
      startPoint: {
        x: 509,
        y: 325,
        id: "14_3",
      },
      sourceNodeId: 14,
      targetNodeId: 15,
    },
    {
      id: "58e3f10b-ed1e-41f8-9e20-4c1ebcf94bc0",
      text: {
        x: 522,
        y: 515.5,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 501,
        y: 570,
        id: "23_0",
      },
      pointsList: [
        {
          x: 524,
          y: 461,
        },
        {
          x: 524,
          y: 515.5,
        },
        {
          x: 501,
          y: 515.5,
        },
        {
          x: 501,
          y: 570,
        },
      ],
      properties: {},
      startPoint: {
        x: 524,
        y: 461,
        id: "20_2",
      },
      sourceNodeId: 20,
      targetNodeId: 23,
    },
    {
      id: "3b0eb1a5-1db8-4d25-9623-4b55d86faf2b",
      text: {
        x: 500,
        y: 647,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 500,
        y: 694,
        id: "25_0",
      },
      pointsList: [
        {
          x: 501,
          y: 600,
        },
        {
          x: 501,
          y: 647,
        },
        {
          x: 500,
          y: 647,
        },
        {
          x: 500,
          y: 694,
        },
      ],
      properties: {},
      startPoint: {
        x: 501,
        y: 600,
        id: "23_2",
      },
      sourceNodeId: 23,
      targetNodeId: 25,
    },
    {
      id: "a3097ea9-cd3b-4157-8abe-f15758d35741",
      text: {
        x: 500,
        y: 950,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 499,
        y: 973,
        id: "51_0",
      },
      pointsList: [
        {
          x: 500,
          y: 920,
        },
        {
          x: 500,
          y: 950,
        },
        {
          x: 499.5,
          y: 950,
        },
        {
          x: 499.5,
          y: 943,
        },
        {
          x: 499,
          y: 943,
        },
        {
          x: 499,
          y: 973,
        },
      ],
      properties: {},
      startPoint: {
        x: 500,
        y: 920,
        id: "26_2",
      },
      sourceNodeId: 26,
      targetNodeId: 51,
    },
    {
      id: "db99539d-e81b-4a0c-8110-03ba3d566e83",
      text: {
        x: 499,
        y: 1035,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 498,
        y: 1067,
        id: "4_0",
      },
      pointsList: [
        {
          x: 499,
          y: 1003,
        },
        {
          x: 499,
          y: 1035,
        },
        {
          x: 498,
          y: 1035,
        },
        {
          x: 498,
          y: 1067,
        },
      ],
      properties: {},
      startPoint: {
        x: 499,
        y: 1003,
        id: "51_2",
      },
      sourceNodeId: 51,
      targetNodeId: 4,
    },
    {
      id: "421e8cea-3758-4dd0-9542-d385234834d8",
      text: {
        x: 498,
        y: 1112,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 498,
        y: 1151,
        id: "5_0",
      },
      pointsList: [
        {
          x: 498,
          y: 1097,
        },
        {
          x: 498,
          y: 1127,
        },
        {
          x: 498,
          y: 1127,
        },
        {
          x: 498,
          y: 1121,
        },
        {
          x: 498,
          y: 1121,
        },
        {
          x: 498,
          y: 1151,
        },
      ],
      properties: {},
      startPoint: {
        x: 498,
        y: 1097,
        id: "4_2",
      },
      sourceNodeId: 4,
      targetNodeId: 5,
    },
    {
      id: "a1e33eb2-c1df-418c-917c-386d844aae09",
      text: {
        x: 500,
        y: 761,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 500,
        y: 798,
        id: "24_0",
      },
      pointsList: [
        {
          x: 500,
          y: 724,
        },
        {
          x: 500,
          y: 798,
        },
      ],
      properties: {},
      startPoint: {
        x: 500,
        y: 724,
        id: "25_2",
      },
      sourceNodeId: 25,
      targetNodeId: 24,
    },
    {
      id: "3bbd0d9b-efd6-4cbf-ba6a-5d18b815ae04",
      text: {
        x: 500,
        y: 859,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 500,
        y: 890,
        id: "26_0",
      },
      pointsList: [
        {
          x: 500,
          y: 828,
        },
        {
          x: 500,
          y: 890,
        },
      ],
      properties: {},
      startPoint: {
        x: 500,
        y: 828,
        id: "24_2",
      },
      sourceNodeId: 24,
      targetNodeId: 26,
    },
    {
      id: "eb73d00e-a16d-46a9-99a5-40fd0bf911ca",
      text: {
        x: 325,
        y: 174,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 325,
        y: 205,
        id: "12_0",
      },
      pointsList: [
        {
          x: 325,
          y: 143,
        },
        {
          x: 325,
          y: 205,
        },
      ],
      properties: {},
      startPoint: {
        x: 325,
        y: 143,
        id: "10_2",
      },
      sourceNodeId: 10,
      targetNodeId: 12,
    },
    {
      id: "5572cb08-64da-4b28-89e0-834126b36fd1",
      text: {
        x: 446.5,
        y: 220,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 508,
        y: 220,
        id: "13_3",
      },
      pointsList: [
        {
          x: 385,
          y: 220,
        },
        {
          x: 508,
          y: 220,
        },
      ],
      properties: {},
      startPoint: {
        x: 385,
        y: 220,
        id: "12_1",
      },
      sourceNodeId: 12,
      targetNodeId: 13,
    },
    {
      id: "466a6b5d-db75-48de-8913-c3f3710130de",
      text: {
        x: 446.5,
        y: 127,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 385,
        y: 128,
        id: "10_1",
      },
      pointsList: [
        {
          x: 508,
          y: 128,
        },
        {
          x: 385,
          y: 128,
        },
      ],
      properties: {},
      startPoint: {
        x: 508,
        y: 128,
        id: "9_3",
      },
      sourceNodeId: 9,
      targetNodeId: 10,
    },
    {
      id: "f3f03c1d-f0a5-478c-b4bf-461d93cc7b39",
      text: {
        x: 319,
        y: 355,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 319,
        y: 396,
        id: "16_0",
      },
      pointsList: [
        {
          x: 319,
          y: 340,
        },
        {
          x: 319,
          y: 370,
        },
        {
          x: 319,
          y: 370,
        },
        {
          x: 319,
          y: 366,
        },
        {
          x: 319,
          y: 366,
        },
        {
          x: 319,
          y: 396,
        },
      ],
      properties: {},
      startPoint: {
        x: 319,
        y: 340,
        id: "15_2",
      },
      sourceNodeId: 15,
      targetNodeId: 16,
    },
    {
      id: "e75dba1d-d354-4421-8809-b7834c7f17f7",
      text: {
        x: 466.5,
        y: 401,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 524,
        y: 431,
      },
      pointsList: [
        {
          x: 379,
          y: 411,
        },
        {
          x: 409,
          y: 411,
        },
        {
          x: 409,
          y: 401,
        },
        {
          x: 524,
          y: 401,
        },
        {
          x: 524,
          y: 431,
        },
      ],
      properties: {},
      startPoint: {
        x: 379,
        y: 411,
      },
      sourceNodeId: 16,
      targetNodeId: 20,
    },
    {
      id: "d9390994-db36-4839-9786-7f45df166386",
      text: {
        x: 390.5,
        y: 446,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 317,
        y: 571,
      },
      pointsList: [
        {
          x: 464,
          y: 446,
        },
        {
          x: 317,
          y: 446,
        },
        {
          x: 317,
          y: 571,
        },
      ],
      properties: {},
      startPoint: {
        x: 464,
        y: 446,
      },
      sourceNodeId: 20,
      targetNodeId: 22,
    },
    {
      id: "564c9f2c-49f3-4370-b3ac-b7fcb7b0e0b6",
      text: {
        x: 686,
        y: 446,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 686,
        y: 568,
      },
      pointsList: [
        {
          x: 584,
          y: 446,
        },
        {
          x: 686,
          y: 446,
        },
        {
          x: 686,
          y: 568,
        },
      ],
      properties: {},
      startPoint: {
        x: 584,
        y: 446,
      },
      sourceNodeId: 20,
      targetNodeId: 21,
    },
    {
      id: "c8dcf01c-be2a-4b89-9df4-bf25bffd17c0",
      text: {
        x: 623,
        y: 709,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 686,
        y: 598,
      },
      pointsList: [
        {
          x: 560,
          y: 709,
        },
        {
          x: 686,
          y: 709,
        },
        {
          x: 686,
          y: 598,
        },
      ],
      properties: {},
      startPoint: {
        x: 560,
        y: 709,
      },
      sourceNodeId: 25,
      targetNodeId: 21,
    },
    {
      id: "3ac48575-89a5-436b-99e6-4b8b4a754222",
      text: {
        x: 378.5,
        y: 709,
        value: "pass",
      },
      type: "polyline",
      endPoint: {
        x: 440,
        y: 709,
      },
      pointsList: [
        {
          x: 317,
          y: 601,
        },
        {
          x: 317,
          y: 709,
        },
        {
          x: 440,
          y: 709,
        },
      ],
      properties: {},
      startPoint: {
        x: 317,
        y: 601,
      },
      sourceNodeId: 22,
      targetNodeId: 25,
    },
  ],
  nodes: [
    {
      x: 320,
      y: 45,
      id: 3,
      text: {
        x: 320,
        y: 45,
        value: "创建订单(1)",
      },
      type: "rect",
      properties: {
        data: {
          id: 3,
          icon: "jxwicon-icon-test",
          name: "创建订单",
          value: "1",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 2,
          pageForm: null,
          updateBy: "",
          createTime: "2024-11-26 21:10:09",
          formConfig:
            '[{"id": 230, "key": "sqzje", "icon": null, "key1": "jkxx", "key2": "jkxx_jbxx", "name": "融资金额(元)", "type": "3", "remark": null, "createBy": "", "formType": "number", "orderNum": 46, "parentId": 224, "picLimit": null, "updateBy": "", "bindValue": "请输入整数", "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 08:56:15"}, {"id": 235, "key": "p5", "icon": null, "key1": "jkxx", "key2": "jkxx_jbxx", "name": "申请期数", "type": "3", "remark": null, "createBy": "", "formType": "pselect", "orderNum": 53, "parentId": 224, "picLimit": null, "updateBy": "", "bindValue": "[\\"12\\",\\"18\\",\\"24\\",\\"36\\"]", "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 08:58:24"}, {"id": 20, "key": "xsz", "icon": null, "key1": "clxx", "key2": "xszinfo", "name": "行驶证(正副页)", "type": "3", "remark": null, "createBy": "", "formType": "pic", "orderNum": 1, "parentId": 19, "picLimit": 2, "updateBy": "", "bindValue": "① 打开《机动车行驶证》，水平放置桌面，主页与副页需展示车辆基本信息内容；", "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 09:10:49"}, {"id": 274, "key": "carnumber", "icon": null, "key1": "clxx", "key2": "clxx_cljbxx", "name": "车牌号", "type": "3", "remark": null, "createBy": "", "formType": "input", "orderNum": 50, "parentId": 270, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 09:40:09"}, {"id": 282, "key": "carvin", "icon": null, "key1": "clxx", "key2": "clxx_cljbxx", "name": "车辆识别代号", "type": "3", "remark": null, "createBy": "", "formType": "input", "orderNum": 430, "parentId": 270, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 09:43:04"}, {"id": 283, "key": "carenginenumber", "icon": null, "key1": "clxx", "key2": "clxx_cljbxx", "name": "发动机号码", "type": "3", "remark": null, "createBy": "", "formType": "input", "orderNum": 440, "parentId": 270, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 09:43:15"}, {"id": 286, "key": "carprodate", "icon": null, "key1": "clxx", "key2": "clxx_cljbxx", "name": "车辆登记日期", "type": "3", "remark": null, "createBy": "", "formType": "pdate", "orderNum": 550, "parentId": 270, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 09:44:30"}, {"id": 291, "key": "carmile", "icon": null, "key1": "clxx", "key2": "clxx_cljbxx", "name": "行驶里程（km）", "type": "3", "remark": null, "createBy": "", "formType": "number", "orderNum": 600, "parentId": 270, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 09:46:16"}, {"id": 83, "key": "sfzzm", "icon": null, "key1": "grxx", "key2": "sfzfile", "name": "身份证正面", "type": "3", "remark": null, "createBy": "", "formType": "pic", "orderNum": 1, "parentId": 82, "picLimit": 1, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 17:07:28"}, {"id": 84, "key": "sfzfm", "icon": null, "key1": "grxx", "key2": "sfzfile", "name": "身份证反面", "type": "3", "remark": null, "createBy": "", "formType": "pic", "orderNum": 2, "parentId": 82, "picLimit": 1, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 17:07:34"}, {"id": 326, "key": "uname", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "客户姓名", "type": "3", "remark": null, "createBy": "", "formType": "input", "orderNum": 1, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:33:33"}, {"id": 327, "key": "usex", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "客户性别", "type": "3", "remark": null, "createBy": "", "formType": "input", "orderNum": 2, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:33:48"}, {"id": 328, "key": "uminorit", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "民族", "type": "3", "remark": null, "createBy": "", "formType": "pselect", "orderNum": 3, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": "[\\"汉\\",\\"蒙古\\",\\"回\\",\\"藏\\",\\"维吾尔\\",\\"苗\\",\\"彝\\",\\"壮\\",\\"布依\\",\\"朝鲜\\",\\"满\\",\\"侗\\",\\"瑶\\",\\"白\\",\\"土家\\",\\"哈尼\\",\\"哈萨克\\",\\"傣\\",\\"黎\\",\\"傈僳\\",\\"佤\\",\\"畲\\",\\"高山\\",\\"拉祜\\",\\"水\\",\\"东乡\\",\\"纳西\\",\\"景颇\\",\\"柯尔克孜\\",\\"土\\",\\"达斡尔\\",\\"仫佬\\",\\"羌\\",\\"布朗\\",\\"撒拉\\",\\"毛南\\",\\"仡佬\\",\\"锡伯\\",\\"阿昌\\",\\"普米\\",\\"塔吉克\\",\\"怒\\",\\"乌孜别克\\",\\"俄罗斯\\",\\"鄂温克\\",\\"德昂\\",\\"保安\\",\\"裕固\\",\\"京\\",\\"塔塔尔\\",\\"独龙\\",\\"鄂伦春\\",\\"赫哲\\",\\"门巴\\",\\"珞巴\\",\\"基诺\\",\\"其它\\",\\"外国血统中国籍人士\\"]", "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:34:08"}, {"id": 329, "key": "ucardno", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "身份证号", "type": "3", "remark": null, "createBy": "", "formType": "input", "orderNum": 4, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:34:28"}, {"id": 330, "key": "ucarddate1", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "身份证起始日期", "type": "3", "remark": null, "createBy": "", "formType": "pdate", "orderNum": 440, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:46:12"}, {"id": 331, "key": "ucarddate2", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "身份证截止日期", "type": "3", "remark": null, "createBy": "", "formType": "pdatecard", "orderNum": 450, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:46:30"}, {"id": 332, "key": "ucarddepart", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "身份证签发机关", "type": "3", "remark": null, "createBy": "", "formType": "input", "orderNum": 460, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:46:56"}, {"id": 334, "key": "umaristate", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "婚姻状况", "type": "3", "remark": null, "createBy": "", "formType": "pselect", "orderNum": 550, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": "[\\"已婚\\",\\"未婚\\",\\"离异\\",\\"丧偶\\"]", "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:47:40"}, {"id": 350, "key": "umobile", "icon": null, "key1": "grxx", "key2": "grxx_jbxx", "name": "手机号", "type": "3", "remark": null, "createBy": "", "formType": "tel", "orderNum": 990, "parentId": 325, "picLimit": null, "updateBy": "", "bindValue": "请输入本人正在使用的手机号", "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 19:57:19"}, {"id": 138, "key": "rlzmz", "icon": null, "key1": "zxcx", "key2": "zxsqfile", "name": "人脸正面照", "type": "3", "remark": null, "createBy": "", "formType": "pic", "orderNum": 4, "parentId": 136, "picLimit": 1, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 13:11:16"}, {"id": 143, "key": "pic_zxtp_54b03a49c07b468", "icon": null, "key1": "zxcx", "key2": "zxtp", "name": "自有征信材料", "type": "3", "remark": null, "createBy": "", "formType": "pic", "orderNum": 100, "parentId": 141, "picLimit": 1, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 13:12:12"}]',
          updateTime: "2024-11-27 08:36:23",
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 498,
      y: 1082,
      id: 4,
      text: {
        x: 498,
        y: 1082,
        value: "归档审核(107)",
      },
      type: "rect",
      properties: {
        data: {
          id: 4,
          icon: "jxwicon-jiaren",
          name: "归档审核",
          value: "107",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 170,
          pageForm: null,
          updateBy: "",
          createTime: "2024-11-27 20:15:46",
          formConfig:
            '[{"id": 216, "key": "pic_gdzlxx_7a73aa5de7a1a51d", "icon": null, "key1": "zlgdxx", "key2": "gdzlxx", "name": "备用钥匙图片", "type": "3", "remark": null, "createBy": "", "formType": "pic", "orderNum": 1, "parentId": 215, "picLimit": 1, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 12:19:00"}, {"id": 217, "key": "pic_gdzlxx_35d70a6315eff375", "icon": null, "key1": "zlgdxx", "key2": "gdzlxx", "name": "验证视频", "type": "3", "remark": null, "createBy": "", "formType": "pic", "orderNum": 2, "parentId": 215, "picLimit": 1, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 12:19:08"}, {"id": 462, "key": "p65", "icon": null, "key1": "zlgdxx", "key2": "gdzlyj", "name": "快递单号", "type": "3", "remark": null, "createBy": "", "formType": "input", "orderNum": 1, "parentId": 461, "picLimit": null, "updateBy": "", "bindValue": null, "parentKey": null, "createTime": null, "picExample": null, "updateTime": "2024-11-20 12:19:32"}]',
          updateTime: "2024-11-27 20:17:12",
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 498,
      y: 1166,
      id: 5,
      text: {
        x: 498,
        y: 1166,
        value: "订单完成(9)",
      },
      type: "rect",
      properties: {
        data: {
          id: 5,
          icon: "jxwicon-wancheng",
          name: "订单完成",
          value: "9",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 500,
          pageForm: null,
          updateBy: "",
          createTime: "2024-11-27 20:19:11",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 1160,
      id: 7,
      text: {
        x: 80,
        y: 1160,
        value: "拒绝(9999)",
      },
      type: "rect",
      properties: {
        data: {
          id: 7,
          icon: "",
          name: "拒绝",
          value: "9999",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 700,
          pageForm: null,
          updateBy: "",
          createTime: "2024-12-01 21:44:50",
          formConfig: null,
          updateTime: "2024-12-12 11:20:59",
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 569,
      y: 45,
      id: 8,
      text: {
        x: 569,
        y: 45,
        value: "授权书签约(60)",
      },
      type: "rect",
      properties: {
        data: {
          id: 8,
          icon: "jxwicon-pengyou",
          name: "授权书签约",
          value: "60",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 2,
          pageForm: "/contractsign2",
          updateBy: "",
          createTime: "2024-12-30 16:34:14",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 568,
      y: 128,
      id: 9,
      text: {
        x: 568,
        y: 128,
        value: "进件预审(66)",
      },
      type: "rect",
      properties: {
        data: {
          id: 9,
          icon: "jxwicon-shenhe-copy",
          name: "进件预审",
          value: "66",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 3,
          pageForm: null,
          updateBy: "",
          createTime: "2025-01-02 14:41:20",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 325,
      y: 128,
      id: 10,
      text: {
        x: 325,
        y: 128,
        value: "车辆信息(15)",
      },
      type: "rect",
      properties: {
        data: {
          id: 10,
          icon: "jxwicon-hetong",
          name: "车辆信息",
          value: "15",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 4,
          pageForm: null,
          updateBy: "",
          createTime: "2025-01-02 14:42:19",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 40,
      id: 11,
      text: {
        x: 80,
        y: 40,
        value: "风控视频面审(99)",
      },
      type: "rect",
      properties: {
        data: {
          id: 11,
          icon: "jxwicon-bianji",
          name: "风控视频面审",
          value: "99",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 4,
          pageForm: null,
          updateBy: "",
          createTime: "2025-01-02 14:43:18",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 325,
      y: 220,
      id: 12,
      text: {
        x: 325,
        y: 220,
        value: "车辆评估(106)",
      },
      type: "rect",
      properties: {
        data: {
          id: 12,
          icon: "jxwicon-hetong",
          name: "车辆评估",
          value: "106",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 5,
          pageForm: null,
          updateBy: "",
          createTime: "2025-01-02 14:43:58",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 568,
      y: 220,
      id: 13,
      text: {
        x: 568,
        y: 220,
        value: "额度确认(80)",
      },
      type: "rect",
      properties: {
        data: {
          id: 13,
          icon: null,
          name: "额度确认",
          value: "80",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 6,
          pageForm: null,
          updateBy: "",
          createTime: "2025-01-02 14:44:46",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 569,
      y: 325,
      id: 14,
      text: {
        x: 569,
        y: 325,
        value: "完善资料(31)",
      },
      type: "rect",
      properties: {
        data: {
          id: 14,
          icon: "jxwicon-zhongshenguanli",
          name: "完善资料",
          value: "31",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 7,
          pageForm: null,
          updateBy: "",
          createTime: "2025-01-02 14:45:25",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 319,
      y: 325,
      id: 15,
      text: {
        x: 319,
        y: 325,
        value: "资料终审(23)",
      },
      type: "rect",
      properties: {
        data: {
          id: 15,
          icon: "jxwicon-shenhe-copy",
          name: "资料终审",
          value: "23",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 8,
          pageForm: null,
          updateBy: "",
          createTime: "2025-01-02 14:46:20",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 319,
      y: 411,
      id: 16,
      text: {
        x: 319,
        y: 411,
        value: "绑卡签约(18)",
      },
      type: "rect",
      properties: {
        data: {
          id: 16,
          icon: "jxwicon-shuaqiaqiapianyinhangqia",
          name: "绑卡签约",
          value: "18",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 9,
          pageForm: "/nodetask",
          updateBy: "",
          createTime: "2025-01-02 14:47:43",
          formConfig: null,
          updateTime: "2025-01-02 14:48:42",
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 160,
      id: 17,
      text: {
        x: 80,
        y: 160,
        value: "资料补录(27)",
      },
      type: "rect",
      properties: {
        data: {
          id: 17,
          icon: "jxwicon-work",
          name: "资料补录",
          value: "27",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 9,
          pageForm: null,
          updateBy: "",
          createTime: "2025-01-02 14:49:11",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 120,
      id: 18,
      text: {
        x: 80,
        y: 120,
        value: "资方合同签署中(101)",
      },
      type: "rect",
      properties: {
        data: {
          id: 18,
          icon: "jxwicon-hetong",
          name: "资方合同签署中",
          value: "101",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 9,
          pageForm: "/zgchtsignform",
          updateBy: "",
          createTime: "2025-01-02 14:50:08",
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 80,
      id: 19,
      text: {
        x: 80,
        y: 80,
        value: "资方合同重签中(102)",
      },
      type: "rect",
      properties: {
        data: {
          id: 19,
          icon: "jxwicon-hetong",
          name: "资方合同重签中",
          value: "102",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 9,
          pageForm: "/zgchtsignform",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 524,
      y: 446,
      id: 20,
      text: {
        x: 524,
        y: 446,
        value: "电子合同签署(24)",
      },
      type: "rect",
      properties: {
        data: {
          id: 20,
          icon: "jxwicon-shipingtonghua",
          name: "电子合同签署",
          value: "24",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 10,
          pageForm: "/contractsign2",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 686,
      y: 583,
      id: 21,
      text: {
        x: 686,
        y: 583,
        value: "视频面签(10)",
      },
      type: "rect",
      properties: {
        data: {
          id: 21,
          icon: "jxwicon-bianji",
          name: "视频面签",
          value: "10",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 11,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 317,
      y: 586,
      id: 22,
      text: {
        x: 317,
        y: 586,
        value: "GPS安装中(4)",
      },
      type: "rect",
      properties: {
        data: {
          id: 22,
          icon: "jxwicon-dizhi",
          name: "GPS安装中",
          value: "4",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 11,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 501,
      y: 585,
      id: 23,
      text: {
        x: 501,
        y: 585,
        value: "抵押办理(19)",
      },
      type: "rect",
      properties: {
        data: {
          id: 23,
          icon: "jxwicon-dongchandiya1",
          name: "抵押办理",
          value: "19",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 11,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 500,
      y: 813,
      id: 24,
      text: {
        x: 500,
        y: 813,
        value: "请款资料补录(20)",
      },
      type: "rect",
      properties: {
        data: {
          id: 24,
          icon: "jxwicon-icon-test1",
          name: "请款资料补录",
          value: "20",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 11,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 500,
      y: 709,
      id: 25,
      text: {
        x: 500,
        y: 709,
        value: "请款审核(25)",
      },
      type: "rect",
      properties: {
        data: {
          id: 25,
          icon: "jxwicon-fangkuan",
          name: "请款审核",
          value: "25",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 12,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 500,
      y: 905,
      id: 26,
      text: {
        x: 500,
        y: 905,
        value: "待放款(21)",
      },
      type: "rect",
      properties: {
        data: {
          id: 26,
          icon: "jxwicon-shenhe-copy",
          name: "待放款",
          value: "21",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 13,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 200,
      id: 27,
      text: {
        x: 80,
        y: 200,
        value: "自主取消(50)",
      },
      type: "rect",
      properties: {
        data: {
          id: 27,
          icon: "",
          name: "自主取消",
          value: "50",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 50,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 240,
      id: 28,
      text: {
        x: 80,
        y: 240,
        value: "拒绝(51)",
      },
      type: "rect",
      properties: {
        data: {
          id: 28,
          icon: "",
          name: "拒绝",
          value: "51",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 51,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 280,
      id: 29,
      text: {
        x: 80,
        y: 280,
        value: "订单关闭(52)",
      },
      type: "rect",
      properties: {
        data: {
          id: 29,
          icon: "",
          name: "订单关闭",
          value: "52",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 52,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 320,
      id: 30,
      text: {
        x: 80,
        y: 320,
        value: "协议签约hz(1)",
      },
      type: "rect",
      properties: {
        data: {
          id: 30,
          icon: "jxwicon-fengkong",
          name: "协议签约hz",
          value: "1",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 100,
          pageForm: "/hzhcbanksign",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 360,
      id: 31,
      text: {
        x: 80,
        y: 360,
        value: "简版征信授权书(17)",
      },
      type: "rect",
      properties: {
        data: {
          id: 31,
          icon: "jxwicon-yanghangzhengxin",
          name: "简版征信授权书",
          value: "17",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 101,
          pageForm: "/jbzxsignform",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 440,
      id: 32,
      text: {
        x: 80,
        y: 440,
        value: "资方预审中(7)",
      },
      type: "rect",
      properties: {
        data: {
          id: 32,
          icon: "jxwicon-shenhe-copy",
          name: "资方预审中",
          value: "7",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 104,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 400,
      id: 33,
      text: {
        x: 80,
        y: 400,
        value: "绑卡协议签约(JCR)2(12)",
      },
      type: "rect",
      properties: {
        data: {
          id: 33,
          icon: "jxwicon-fengkong",
          name: "绑卡协议签约(JCR)2",
          value: "12",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 104,
          pageForm: "/hzhcjcrbanksign2",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 480,
      id: 34,
      text: {
        x: 80,
        y: 480,
        value: "绑卡协议签约(ZGC)1(14)",
      },
      type: "rect",
      properties: {
        data: {
          id: 34,
          icon: "jxwicon-fengkong",
          name: "绑卡协议签约(ZGC)1",
          value: "14",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 105,
          pageForm: "/hzhczgcbanksign1",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 520,
      id: 35,
      text: {
        x: 80,
        y: 520,
        value: "电核(3)",
      },
      type: "rect",
      properties: {
        data: {
          id: 35,
          icon: "jxwicon-cheliangdangan",
          name: "电核",
          value: "3",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 106,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 560,
      id: 36,
      text: {
        x: 80,
        y: 560,
        value: "资方授信中(26)",
      },
      type: "rect",
      properties: {
        data: {
          id: 36,
          icon: "jxwicon-work",
          name: "资方授信中",
          value: "26",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 107,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 600,
      id: 37,
      text: {
        x: 80,
        y: 600,
        value: "资方用信中(2)",
      },
      type: "rect",
      properties: {
        data: {
          id: 37,
          icon: "jxwicon-yanghangzhengxin",
          name: "资方用信中",
          value: "2",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 108,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 640,
      id: 38,
      text: {
        x: 80,
        y: 640,
        value: "绑卡协议签约(JCR)1(11)",
      },
      type: "rect",
      properties: {
        data: {
          id: 38,
          icon: "jxwicon-fengkong",
          name: "绑卡协议签约(JCR)1",
          value: "11",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 109,
          pageForm: "/hzhcjcrbanksign1",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 680,
      id: 39,
      text: {
        x: 80,
        y: 680,
        value: "合同审核(41)",
      },
      type: "rect",
      properties: {
        data: {
          id: 39,
          icon: "jxwicon-shipingtonghua",
          name: "合同审核",
          value: "41",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 110,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 720,
      id: 40,
      text: {
        x: 80,
        y: 720,
        value: "装G下单(201)",
      },
      type: "rect",
      properties: {
        data: {
          id: 40,
          icon: "jxwicon-icon_azgps",
          name: "装G下单",
          value: "201",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 111,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 760,
      id: 41,
      text: {
        x: 80,
        y: 760,
        value: "办押下单(22)",
      },
      type: "rect",
      properties: {
        data: {
          id: 41,
          icon: "jxwicon-dongchandiya1",
          name: "办押下单",
          value: "22",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 112,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 800,
      id: 42,
      text: {
        x: 80,
        y: 800,
        value: "装G办押(81)",
      },
      type: "rect",
      properties: {
        data: {
          id: 42,
          icon: "jxwicon-dongchandiya1",
          name: "装G办押",
          value: "81",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 113,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 840,
      id: 43,
      text: {
        x: 80,
        y: 840,
        value: "终审(105)",
      },
      type: "rect",
      properties: {
        data: {
          id: 43,
          icon: "jxwicon-shenhe-copy",
          name: "终审",
          value: "105",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 114,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 880,
      id: 44,
      text: {
        x: 80,
        y: 880,
        value: "抵押办理中(61)",
      },
      type: "rect",
      properties: {
        data: {
          id: 44,
          icon: "",
          name: "抵押办理中",
          value: "61",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 115,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 920,
      id: 45,
      text: {
        x: 80,
        y: 920,
        value: "资方车务确认中(16)",
      },
      type: "rect",
      properties: {
        data: {
          id: 45,
          icon: "jxwicon-shenhe-copy",
          name: "资方车务确认中",
          value: "16",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 116,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 960,
      id: 46,
      text: {
        x: 80,
        y: 960,
        value: "装G办押中(82)",
      },
      type: "rect",
      properties: {
        data: {
          id: 46,
          icon: "jxwicon-dongchandiya1",
          name: "装G办押中",
          value: "82",
          isBack: "0",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 117,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 1000,
      id: 47,
      text: {
        x: 80,
        y: 1000,
        value: "放款申请(8)",
      },
      type: "rect",
      properties: {
        data: {
          id: 47,
          icon: "jxwicon-fangkuan",
          name: "放款申请",
          value: "8",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 118,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 1040,
      id: 48,
      text: {
        x: 80,
        y: 1040,
        value: "重新用信审核中(28)",
      },
      type: "rect",
      properties: {
        data: {
          id: 48,
          icon: "jxwicon-yanghangzhengxin",
          name: "重新用信审核中",
          value: "28",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 130,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 1080,
      id: 49,
      text: {
        x: 80,
        y: 1080,
        value: "抵押重新确认中(200)",
      },
      type: "rect",
      properties: {
        data: {
          id: 49,
          icon: "jxwicon-shenhe-copy",
          name: "抵押重新确认中",
          value: "200",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "1",
          orderNum: 140,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 140,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 80,
      y: 1120,
      id: 50,
      text: {
        x: 80,
        y: 1120,
        value: "资方放款中(5)",
      },
      type: "rect",
      properties: {
        data: {
          id: 50,
          icon: "jxwicon-fangkuan",
          name: "资方放款中",
          value: "5",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 150,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
    {
      x: 499,
      y: 988,
      id: 51,
      text: {
        x: 499,
        y: 988,
        value: "待资料归档(6)",
      },
      type: "rect",
      properties: {
        data: {
          id: 51,
          icon: "jxwicon-zhongshenguanli",
          name: "待资料归档",
          value: "6",
          isBack: "1",
          remark: null,
          delFlag: "0",
          createBy: "",
          isReject: "0",
          orderNum: 160,
          pageForm: "",
          updateBy: "",
          createTime: null,
          formConfig: null,
          updateTime: null,
          approvalTime: 0,
        },
        width: 120,
        height: 30,
        radius: 20,
      },
    },
  ],
};
